# Travis CI configuration for pg_seldump

language: python

matrix:
  include:

    - env: TOXENV=py35
      python: 3.5

    - env: TOXENV=py36
      python: 3.6

    - env: TOXENV=py37
      python: 3.7

    - env: TOXENV=py38
      python: 3.8

    - env: TOXENV=black
      python: 3.6

    - env: TOXENV=flake8
      python: 3.5

install:
  - pip install tox

script:
  - tox
