# Travis CI configuration for pg_seldump

language: python

matrix:
  include:

    - env: TOXENV=black
      python: 3.6

    - env: TOXENV=flake8
      python: 3.5

    - env: TOXENV=py35
      python: 3.5
      addons:
        postgresql: '9.5'
        apt:
          packages:
            - postgresql-client-9.5

    - env: TOXENV=py36
      python: 3.6
      addons:
        postgresql: '9.6'
        apt:
          packages:
            - postgresql-client-9.6

    - env: TOXENV=py37
      python: 3.7
      addons:
        postgresql: '10'
        apt:
          packages:
            - postgresql-client-10

    - python: 3.8
      addons:
        postgresql: '11'
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
      env:
        - TOXENV=py38
        - PGPORT=5433

    - python: 3.8
      addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - TOXENV=py38
        - PGPORT=5433

install:
  - pip install tox
  - test ${TOXENV:0:2} != py || psql -c 'create database seldump_test'

script:
  - tox -- --test-dsn dbname=seldump_test
